name: useragents scraper

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scraps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false

      - run: go install github.com/gebleksengek/useragents-scraper@latest

      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false
      
      - run: useragents-scraper -output useragents.json
        
      - run: |
          git config --local user.email "${{ secrets.GH_EMAIL }}"
          git config --local user.name "${{ secrets.GH_NAME }}"
          git add -A
          git commit -m "update useragents.json"     
      
      - uses: ad-m/github-push-action@master
        with:
          branch: main
          force: true
          github_token: ${{ secrets.GH_TOKEN }}
